# Generated by Django 4.0 on 2022-01-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mores', '0002_rate_delete_rateus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='stars2',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='stars3',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='stars4',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='stars5',
        ),
    ]
