# Generated by Django 4.0 on 2022-01-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mores', '0006_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='updates',
            new_name='whatsnew',
        ),
    ]
