# Generated by Django 4.0 on 2022-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mores', '0007_rename_updates_whatsnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsnew',
            name='update',
            field=models.TextField(),
        ),
    ]
