# Generated by Django 4.0 on 2022-01-19 11:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mores', '0008_alter_whatsnew_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsnew',
            name='update',
            field=tinymce.models.HTMLField(),
        ),
    ]
