# Generated by Django 4.0 on 2022-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_description_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cType',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
